class Dicas {
  static String dicaCalibragem =
      'Todo carro traz a informação sobre a calibragem correta a ser utilizada. Ela aparece em algum lugar da carroceria (às vezes no batente da porta do motorista, às vezes na tampa do tanque de combustível) e no manual do proprietário. Há casos em que o fabricante recomenda pressão diferente nos dianteiros e nos traseiros.\n\nCada veículo tem sua calibragem especificada pelo fabricante. As fábricas estimam que 10% abaixo da indicada significará redução de 5% na vida útil. Se estiver 20% abaixo do ideal, a expectativa de vida cai 16%. Rodando 30% mais murcho, ele pode durar 33% a menos. E, como pressão correta é fundamental para a estabilidade, não deixe de verificá-la semanalmente, ou a cada vez que for abastecer o automóvel.';

  static String dicaRodagemPneus =
      'Cada fabricante determina um prazo ideal para o rodízio entre os pneus. Sua função é uniformizar o desgaste entre os dianteiros e os traseiros. Em função do peso do veículo (em geral concentrado na frente) e da tração (também dianteira na maioria dos casos), os pneus frontais costumam sofrer três vezes mais desgaste que a dupla que roda atrás. Por isso, na média recomenda-se a troca de posições a cada 10 000 km. Mas convém consultar o manual em busca da recomendação oficial.';

  static String dicaAlinhamento =
      'Sabe quando você solta o volante e o carro puxa para um lado? É sintoma de direção desalinhada, que abrevia a vida útil do pneu. Quando isso ocorre, ele está sendo mais sobrecarregado que o outro. O sintoma é desgaste acelerado e desigual. A cambagem incorreta acelera o desgaste nos ombros: normalmente, a roda forma um ângulo de 90 graus em relação ao piso, mas cada projeto de automóvel tem uma especificação. Se a falha não for corrigida, os pneus podem ter muita borracha numa determinada área da banda de rodagem e estar carecas em outra. Se for assim, é o fim da linha para ele.';
}